//! Signaling envelope: wire format, encoding, and bounds-checked decoding.
//!
//! # Wire layout (big-endian throughout)
//!
//! ```text
//! Offset  Len   Field
//! 0       1     kind: u8   (0=Hello … 6=Error)
//! 1       16    session_id: [u8; 16]
//! 17      64    from_fp:   [u8; 64]  (UTF-8 ASCII hex fingerprint, 64 chars)
//! 81      64    to_fp:     [u8; 64]  (same)
//! 145     4     payload_len: u32 BE
//! 149     N     opaque_payload (N = payload_len, max MAX_PAYLOAD_LEN)
//! ```
//!
//! The server MUST NOT inspect `opaque_payload` for routing; it uses only `session_id`
//! and `to_fp`. This is the zero-knowledge relay invariant (LLD §6.3).

use bytes::{BufMut, Bytes, BytesMut};

use crate::error::SignalingError;

/// Maximum opaque payload length accepted in a single envelope (64 KiB).
///
/// Payloads larger than this are rejected at decode time to prevent memory amplification
/// attacks from hostile peers that declare absurd lengths.
pub const MAX_PAYLOAD_LEN: u32 = 64 * 1024;

/// Fixed byte length of the envelope header (everything before the payload).
///
/// ```text
/// 1 (kind) + 16 (session_id) + 64 (from_fp) + 64 (to_fp) + 4 (payload_len) = 149
/// ```
pub const ENVELOPE_HEADER_LEN: usize = 149;

/// Offset of `from_fp` in the wire format.
const FROM_FP_OFFSET: usize = 17;
/// Offset of `to_fp` in the wire format.
const TO_FP_OFFSET: usize = 81;
/// Offset of `payload_len` in the wire format.
const PAYLOAD_LEN_OFFSET: usize = 145;
/// Length of each fingerprint field on the wire.
const FP_LEN: usize = 64;

/// Kind discriminant for a [`SignalingEnvelope`].
///
/// Values 0–6 are defined; all other byte values are rejected at decode time.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MessageKind {
    /// Client registration — sent immediately after connecting to announce `(session_id, from_fp)`.
    Hello = 0,
    /// Initiator's SDP offer; payload is an opaque blob (SDP text, BindCert, etc.).
    Offer = 1,
    /// Responder's SDP answer; payload is an opaque blob.
    Answer = 2,
    /// Trickle-ICE candidate; payload is an opaque candidate blob.
    Candidate = 3,
    /// End-of-candidates signal for one direction; payload is empty.
    EndOfCandidates = 4,
    /// Graceful disconnect.
    Bye = 5,
    /// Server-to-client error; payload is a UTF-8 ASCII error string.
    Error = 6,
}

impl MessageKind {
    /// Converts a raw byte to a `MessageKind`.
    ///
    /// # Errors
    ///
    /// Returns [`SignalingError::UnknownMessageKind`] if `byte` is not in 0–6.
    pub(crate) fn from_u8(byte: u8) -> Result<Self, SignalingError> {
        match byte {
            0 => Ok(Self::Hello),
            1 => Ok(Self::Offer),
            2 => Ok(Self::Answer),
            3 => Ok(Self::Candidate),
            4 => Ok(Self::EndOfCandidates),
            5 => Ok(Self::Bye),
            6 => Ok(Self::Error),
            other => Err(SignalingError::UnknownMessageKind { byte: other }),
        }
    }
}

/// Opaque 16-byte session token that scopes a signaling rendezvous.
///
/// The token is generated by the session initiator and shared out-of-band (e.g. via a pairing
/// QR code) with the responder. The server routes within a session by `(session_id, fingerprint)`.
///
/// # Examples
///
/// ```
/// use sh_signaling::SessionId;
///
/// let id = SessionId([0u8; 16]);
/// assert_eq!(id.as_bytes(), &[0u8; 16]);
/// ```
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct SessionId(pub [u8; 16]);

impl SessionId {
    /// Returns the raw bytes of this session ID.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8; 16] {
        &self.0
    }
}

impl std::fmt::Debug for SessionId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Show only the first 4 bytes in hex to avoid full token exposure in logs.
        write!(
            f,
            "SessionId({:02x}{:02x}{:02x}{:02x}…)",
            self.0[0], self.0[1], self.0[2], self.0[3]
        )
    }
}

/// A signaling message routed between two peers via the signaling server.
///
/// The server routes this envelope using only `session_id` and `to_fp`. The `payload` is
/// **opaque**: the server MUST NOT parse it (zero-knowledge boundary, LLD §6.3).
///
/// # Wire format
///
/// See [`ENVELOPE_HEADER_LEN`] for the exact layout. Big-endian throughout.
///
/// # Examples
///
/// ```
/// use bytes::Bytes;
/// use sh_signaling::{MessageKind, SessionId, SignalingEnvelope};
/// use sh_signaling::envelope::{encode, decode};
///
/// let env = SignalingEnvelope {
///     kind: MessageKind::Hello,
///     session_id: SessionId([1u8; 16]),
///     from_fp: "a".repeat(64),
///     to_fp: "b".repeat(64),
///     payload: Bytes::new(),
/// };
/// let encoded = encode(&env).unwrap();
/// let decoded = decode(&encoded).unwrap();
/// assert_eq!(decoded.kind, MessageKind::Hello);
/// assert_eq!(decoded.from_fp, "a".repeat(64));
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SignalingEnvelope {
    /// The kind of message.
    pub kind: MessageKind,
    /// Session scope — both peers must present the same session ID.
    pub session_id: SessionId,
    /// Sender's fingerprint (64-char lowercase hex).
    pub from_fp: String,
    /// Recipient's fingerprint (64-char lowercase hex).
    pub to_fp: String,
    /// Opaque payload; the server never parses this.
    pub payload: Bytes,
}

/// Validates that a fingerprint string is exactly 64 ASCII characters.
///
/// We do not validate hex content here because the relay does not interpret fingerprints
/// beyond using them as routing keys. Full validation (hex chars, valid public key) is
/// the caller's responsibility before constructing a `DeviceIdentity`.
fn validate_fp(fp: &str) -> Result<(), SignalingError> {
    if fp.len() != FP_LEN || !fp.is_ascii() {
        return Err(SignalingError::InvalidFingerprint);
    }
    Ok(())
}

/// Encode a [`SignalingEnvelope`] to its wire representation.
///
/// A single `BytesMut` is pre-allocated to `ENVELOPE_HEADER_LEN + payload.len()` and
/// written in one pass — minimal allocations.
///
/// # Errors
///
/// - [`SignalingError::PayloadTooLarge`] if `env.payload.len()` exceeds [`MAX_PAYLOAD_LEN`].
/// - [`SignalingError::InvalidFingerprint`] if either fingerprint is not exactly 64 ASCII bytes.
pub fn encode(env: &SignalingEnvelope) -> Result<Bytes, SignalingError> {
    // Validate payload length.
    let payload_len_usize = env.payload.len();
    if payload_len_usize > MAX_PAYLOAD_LEN as usize {
        return Err(SignalingError::PayloadTooLarge {
            len: payload_len_usize as u64,
        });
    }
    // Safe: we just verified it fits in u32.
    #[allow(clippy::cast_possible_truncation)]
    let payload_len_u32 = payload_len_usize as u32;

    // Validate fingerprints.
    validate_fp(&env.from_fp)?;
    validate_fp(&env.to_fp)?;

    let total = ENVELOPE_HEADER_LEN.checked_add(payload_len_usize).ok_or(
        SignalingError::PayloadTooLarge {
            len: payload_len_usize as u64,
        },
    )?;
    let mut buf = BytesMut::with_capacity(total);

    buf.put_u8(env.kind as u8);
    buf.put_slice(env.session_id.as_bytes());
    buf.put_slice(env.from_fp.as_bytes());
    buf.put_slice(env.to_fp.as_bytes());
    buf.put_u32(payload_len_u32);
    buf.put_slice(&env.payload);

    Ok(buf.freeze())
}

/// Decode a [`SignalingEnvelope`] from raw bytes.
///
/// Treats the input as hostile: checks bounds at every step, rejects unknown kind bytes,
/// oversized payloads, and non-ASCII fingerprints. Never panics.
///
/// # Errors
///
/// - [`SignalingError::EnvelopeTooShort`] — `buf.len() < ENVELOPE_HEADER_LEN`
/// - [`SignalingError::UnknownMessageKind`] — kind byte not in 0–6
/// - [`SignalingError::PayloadTooLarge`] — declared `payload_len > MAX_PAYLOAD_LEN`
/// - [`SignalingError::TruncatedPayload`] — buf is shorter than header + `payload_len`
/// - [`SignalingError::InvalidFingerprint`] — fingerprint bytes are not valid ASCII
pub fn decode(buf: &[u8]) -> Result<SignalingEnvelope, SignalingError> {
    if buf.len() < ENVELOPE_HEADER_LEN {
        return Err(SignalingError::EnvelopeTooShort { actual: buf.len() });
    }

    // kind byte — buf.len() >= ENVELOPE_HEADER_LEN (checked above), so index 0 is valid.
    let kind = MessageKind::from_u8(
        *buf.first()
            .ok_or(SignalingError::EnvelopeTooShort { actual: 0 })?,
    )?;

    // session_id: bytes 1..17
    let mut session_bytes = [0u8; 16];
    session_bytes.copy_from_slice(
        buf.get(1..17)
            .ok_or(SignalingError::EnvelopeTooShort { actual: buf.len() })?,
    );
    let session_id = SessionId(session_bytes);

    // from_fp: bytes 17..81
    let from_fp_bytes = buf
        .get(FROM_FP_OFFSET..FROM_FP_OFFSET + FP_LEN)
        .ok_or(SignalingError::EnvelopeTooShort { actual: buf.len() })?;
    let from_fp =
        std::str::from_utf8(from_fp_bytes).map_err(|_| SignalingError::InvalidFingerprint)?;
    validate_fp(from_fp)?;

    // to_fp: bytes 81..145
    let to_fp_bytes = buf
        .get(TO_FP_OFFSET..TO_FP_OFFSET + FP_LEN)
        .ok_or(SignalingError::EnvelopeTooShort { actual: buf.len() })?;
    let to_fp = std::str::from_utf8(to_fp_bytes).map_err(|_| SignalingError::InvalidFingerprint)?;
    validate_fp(to_fp)?;

    // payload_len: bytes 145..149 (u32 BE)
    let len_bytes: [u8; 4] = buf
        .get(PAYLOAD_LEN_OFFSET..PAYLOAD_LEN_OFFSET + 4)
        .ok_or(SignalingError::EnvelopeTooShort { actual: buf.len() })?
        .try_into()
        .map_err(|_| SignalingError::EnvelopeTooShort { actual: buf.len() })?;
    let payload_len = u32::from_be_bytes(len_bytes);

    if payload_len > MAX_PAYLOAD_LEN {
        return Err(SignalingError::PayloadTooLarge {
            len: u64::from(payload_len),
        });
    }

    // payload
    let payload_start = ENVELOPE_HEADER_LEN;
    let available = buf.len().saturating_sub(payload_start);
    let payload_len_usize = payload_len as usize;
    if available < payload_len_usize {
        return Err(SignalingError::TruncatedPayload {
            declared: payload_len,
            available,
        });
    }

    // payload_start + payload_len_usize: safe because we checked available >= payload_len_usize
    // and available = buf.len() - payload_start, so payload_start + payload_len_usize <= buf.len().
    let payload_end = payload_start.saturating_add(payload_len_usize);
    let payload_slice =
        buf.get(payload_start..payload_end)
            .ok_or(SignalingError::TruncatedPayload {
                declared: payload_len,
                available,
            })?;

    Ok(SignalingEnvelope {
        kind,
        session_id,
        from_fp: from_fp.to_owned(),
        to_fp: to_fp.to_owned(),
        payload: Bytes::copy_from_slice(payload_slice),
    })
}

/// Fuzz seam: pure decode of a raw byte slice, for cargo-fuzz.
///
/// Calls [`decode`] and returns the result. Its sole purpose is to be a stable entry-point
/// for the fuzz target. It must never panic regardless of input.
///
/// # Errors
///
/// Propagates any [`SignalingError`] from [`decode`]. The fuzz target discards the result;
/// it only cares that no panic occurs.
pub fn fuzz_decode_envelope(data: &[u8]) -> Result<SignalingEnvelope, SignalingError> {
    decode(data)
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
#[allow(clippy::indexing_slicing)]
#[allow(clippy::manual_repeat_n)]
mod tests {
    use super::*;

    fn make_fp(c: char) -> String {
        std::iter::repeat(c).take(64).collect()
    }

    fn make_env(kind: MessageKind, payload: &[u8]) -> SignalingEnvelope {
        SignalingEnvelope {
            kind,
            session_id: SessionId([0xAB; 16]),
            from_fp: make_fp('a'),
            to_fp: make_fp('b'),
            payload: Bytes::copy_from_slice(payload),
        }
    }

    #[test]
    fn round_trip_hello() {
        let env = make_env(MessageKind::Hello, b"");
        let encoded = encode(&env).unwrap();
        assert_eq!(encoded.len(), ENVELOPE_HEADER_LEN);
        let decoded = decode(&encoded).unwrap();
        assert_eq!(decoded, env);
    }

    #[test]
    fn round_trip_offer_with_payload() {
        let payload = b"v=0\r\no=- 0 0 IN IP4 127.0.0.1\r\n";
        let env = make_env(MessageKind::Offer, payload);
        let encoded = encode(&env).unwrap();
        assert_eq!(encoded.len(), ENVELOPE_HEADER_LEN + payload.len());
        let decoded = decode(&encoded).unwrap();
        assert_eq!(decoded, env);
    }

    #[test]
    fn decode_too_short_returns_error() {
        let buf = vec![0u8; ENVELOPE_HEADER_LEN - 1];
        let err = decode(&buf).unwrap_err();
        assert!(matches!(err, SignalingError::EnvelopeTooShort { .. }));
    }

    #[test]
    fn decode_unknown_kind_returns_error() {
        let env = make_env(MessageKind::Hello, b"");
        let mut encoded = encode(&env).unwrap().to_vec();
        encoded[0] = 0xFF;
        let err = decode(&encoded).unwrap_err();
        assert!(matches!(
            err,
            SignalingError::UnknownMessageKind { byte: 0xFF }
        ));
    }

    #[test]
    fn decode_payload_too_large() {
        let env = make_env(MessageKind::Hello, b"");
        let mut encoded = encode(&env).unwrap().to_vec();
        // Set payload_len to MAX_PAYLOAD_LEN + 1.
        let too_big = (MAX_PAYLOAD_LEN + 1).to_be_bytes();
        encoded[PAYLOAD_LEN_OFFSET] = too_big[0];
        encoded[PAYLOAD_LEN_OFFSET + 1] = too_big[1];
        encoded[PAYLOAD_LEN_OFFSET + 2] = too_big[2];
        encoded[PAYLOAD_LEN_OFFSET + 3] = too_big[3];
        let err = decode(&encoded).unwrap_err();
        assert!(matches!(err, SignalingError::PayloadTooLarge { .. }));
    }

    #[test]
    fn decode_truncated_payload() {
        let payload = b"hello world";
        let env = make_env(MessageKind::Offer, payload);
        let encoded = encode(&env).unwrap().to_vec();
        // Remove last 5 bytes to truncate the payload.
        let truncated = &encoded[..encoded.len() - 5];
        let err = decode(truncated).unwrap_err();
        assert!(matches!(err, SignalingError::TruncatedPayload { .. }));
    }

    #[test]
    fn encode_rejects_invalid_fingerprint() {
        let mut env = make_env(MessageKind::Hello, b"");
        env.from_fp = "short".to_owned();
        let err = encode(&env).unwrap_err();
        assert!(matches!(err, SignalingError::InvalidFingerprint));
    }

    #[test]
    fn encode_rejects_oversized_payload() {
        let big_payload = vec![0u8; MAX_PAYLOAD_LEN as usize + 1];
        let env = make_env(MessageKind::Offer, &big_payload);
        let err = encode(&env).unwrap_err();
        assert!(matches!(err, SignalingError::PayloadTooLarge { .. }));
    }

    #[test]
    fn all_message_kinds_round_trip() {
        let kinds = [
            MessageKind::Hello,
            MessageKind::Offer,
            MessageKind::Answer,
            MessageKind::Candidate,
            MessageKind::EndOfCandidates,
            MessageKind::Bye,
            MessageKind::Error,
        ];
        for kind in kinds {
            let env = make_env(kind, b"test payload");
            let encoded = encode(&env).unwrap();
            let decoded = decode(&encoded).unwrap();
            assert_eq!(decoded.kind, kind);
        }
    }

    #[test]
    fn session_id_debug_shows_partial() {
        let id = SessionId([0xDE, 0xAD, 0xBE, 0xEF, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
        let s = format!("{id:?}");
        assert!(s.contains("deadbeef"), "expected short hex in debug: {s}");
    }

    #[test]
    fn fuzz_seam_no_panic_on_garbage() {
        // Should return an error, not panic.
        let _ = fuzz_decode_envelope(&[0xFF; 200]);
        let _ = fuzz_decode_envelope(&[]);
        let _ = fuzz_decode_envelope(b"garbage");
    }
}
